repos: 
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: ['.', '--config', '.pre-commit/.flake8-conf']
    - id: bandit
      name: bandit
      entry: bandit
      language: system
      types: [python]
      args: ['-c', '.pre-commit/bandit-conf.yaml']
    # - id: pytest
    #   name: pytest
    #   entry: pytest
    #   language: system
    #   types: [python]
